# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VesselTracker
                                 A QGIS plugin
 Displays vessels AIS position in real time
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-04
        copyright            : (C) 2025 by Reach Subsea
        email                : vicente.danvila@reachsubsea.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VesselTracker class from file VesselTracker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .VesselTracker import VesselTracker
    return VesselTracker(iface)
