# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VesselInputDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VesselInputDialog(object):
    def setupUi(self, VesselInputDialog):
        VesselInputDialog.setObjectName("VesselInputDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(VesselInputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableVessels = QtWidgets.QTableWidget(VesselInputDialog)
        self.tableVessels.setColumnCount(2)
        self.tableVessels.setRowCount(0)
        self.tableVessels.setObjectName("tableVessels")
        item = QtWidgets.QTableWidgetItem()
        self.tableVessels.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVessels.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableVessels)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.btnAdd = QtWidgets.QPushButton(VesselInputDialog)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayoutButtons.addWidget(self.btnAdd)
        self.btnRemove = QtWidgets.QPushButton(VesselInputDialog)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayoutButtons.addWidget(self.btnRemove)
        self.verticalLayout.addLayout(self.horizontalLayoutButtons)
        self.buttonBox = QtWidgets.QDialogButtonBox(VesselInputDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(VesselInputDialog)
        QtCore.QMetaObject.connectSlotsByName(VesselInputDialog)

    def retranslateUi(self, VesselInputDialog):
        _translate = QtCore.QCoreApplication.translate
        VesselInputDialog.setWindowTitle(_translate("VesselInputDialog", "Vessel Tracker – Select Vessels"))
        item = self.tableVessels.horizontalHeaderItem(0)
        item.setText(_translate("VesselInputDialog", "MMSI"))
        item = self.tableVessels.horizontalHeaderItem(1)
        item.setText(_translate("VesselInputDialog", "Name"))
        self.btnAdd.setText(_translate("VesselInputDialog", "Add"))
        self.btnRemove.setText(_translate("VesselInputDialog", "Remove"))
