# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VesselInputDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VesselInputDialog(object):
    def setupUi(self, VesselInputDialog):
        VesselInputDialog.setObjectName("VesselInputDialog")
        VesselInputDialog.resize(400, 300) # Adjusted size for the new field
        self.verticalLayout = QtWidgets.QVBoxLayout(VesselInputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # --- START: Added API Key Widgets ---
        self.apiKeyLayout = QtWidgets.QHBoxLayout()
        self.apiKeyLayout.setObjectName("apiKeyLayout")
        self.labelApiKey = QtWidgets.QLabel(VesselInputDialog)
        self.labelApiKey.setObjectName("labelApiKey")
        self.apiKeyLayout.addWidget(self.labelApiKey)
        self.leApiKey = QtWidgets.QLineEdit(VesselInputDialog)
        self.leApiKey.setObjectName("leApiKey")
        self.apiKeyLayout.addWidget(self.leApiKey)
        self.verticalLayout.addLayout(self.apiKeyLayout)
        # --- END: Added API Key Widgets ---
        
        self.tableVessels = QtWidgets.QTableWidget(VesselInputDialog)
        self.tableVessels.setColumnCount(2)
        self.tableVessels.setRowCount(0)
        self.tableVessels.setObjectName("tableVessels")
        item = QtWidgets.QTableWidgetItem()
        self.tableVessels.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVessels.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableVessels)
        
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.btnAdd = QtWidgets.QPushButton(VesselInputDialog)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayoutButtons.addWidget(self.btnAdd)
        self.btnRemove = QtWidgets.QPushButton(VesselInputDialog)
        self.btnRemove.setObjectName("btnRemove")
        self.horizontalLayoutButtons.addWidget(self.btnRemove)
        self.verticalLayout.addLayout(self.horizontalLayoutButtons)
        
        self.buttonBox = QtWidgets.QDialogButtonBox(VesselInputDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(VesselInputDialog)
        self.buttonBox.accepted.connect(VesselInputDialog.accept)
        self.buttonBox.rejected.connect(VesselInputDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(VesselInputDialog)

    def retranslateUi(self, VesselInputDialog):
        _translate = QtCore.QCoreApplication.translate
        VesselInputDialog.setWindowTitle(_translate("VesselInputDialog", "Vessel Tracker – Configuration"))
        
        # --- START: Added API Key Text ---
        self.labelApiKey.setText(_translate("VesselInputDialog", "AIS Stream API Key:"))
        # --- END: Added API Key Text ---
        
        item = self.tableVessels.horizontalHeaderItem(0)
        item.setText(_translate("VesselInputDialog", "MMSI"))
        item = self.tableVessels.horizontalHeaderItem(1)
        item.setText(_translate("VesselInputDialog", "Name"))
        
        self.btnAdd.setText(_translate("VesselInputDialog", "Add"))
        self.btnRemove.setText(_translate("VesselInputDialog", "Remove"))
